

#print_head "Update redis listen address"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/redis.conf /etc/redis/redis.conf &>>${log_file}
#status_check $?
#
#print_head "Enable redis service"
#systemctl enable redis
#status_check $?
#
#print_head "Start redis service"
#systemctl restart redis
#status_check $?
#
#

- name: Install Redis Repos
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

- name: Enable & Install redis
  ansible.builtin.dnf:
    name: '@redis:remi-6.2'
    state: installed

- name: Update Redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0.0'

- name: Start Redis Service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: true
