
#print_head "Update MongoDB Listen Address"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>${log_file}
#status_check $?
#
#print_head "Enable MongoDB Service"
#systemctl enable mongod &>>${log_file}
#status_check $?
#
#print_head "Start MongoDB Service"
#systemctl restart mongod &>>${log_file}
#status_check $?
#
##update  /etc/mongod.conf file from 127.0.0.1 with  0.0.0.0

- name: Setup MongoDB Repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update Mongodb Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true