
#print_head "Copying the Nginx config for roboshop"
#cp ${code_dir}/configs/nginx-roboshop.conf /etc/nginx/default.d/roboshop.conf &>>${log_file}
#status_check $?
#
#print_head "Enabling Nginx"
#systemctl enable nginx &>>${log_file}
#status_check $?
#
#print_head "Starting Nginx"
#systemctl restart nginx &>>${log_file}
#status_check $?
#
## if any command is error or failed , we need stop the script
##status of command need to be printed

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    mode: '0755'

- name: Download and Extract the frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Create Roboshop Config in Nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dst: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes








