
- name: Setup Erlang Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Setup RabbitMQ Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Rabbitmq & Erlang
  ansible.builtin.yum:            # yum module supports lost of packages
    name:
      - rabbitmq-server
      - erlang
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: {{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.amqp_user' , region='us-east-1') }}  ##roboshop
    password: {{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.amqp_pass' , region='us-east-1') }} ##roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
