- name: Copy Logstash Configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Check Logstash Started or not
  ansible.builtin.shell: sleep 60 ; netstat -lntp | grep 5044   # 5044 logstasth port number 