- name: Update prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update prometheus Configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"      # declared in vars folder

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check Prometheus is Started
  ansible.builtin.shell: netstat -lntp | grep 9090

# alert manager
- name: Update AlertManager Configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Check alertmanager is Started
  ansible.builtin.shell: netstat -lntp | grep 9093