- name: MongoDB Schema
  when: schema_type" == "mongo"
  block:
    - name: Setup MongoDB Repo File
      ansible.builtin.copy:
        src: monogdb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install  Mongo Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb-dev.devopsm71.online </app/schema/{{component}}.js

- name: Mysql Schema
  when: schema_type" == "mysql"
  block:
    - name: Install Mysql Client
      ansible.builtin.yum:
      name: mysql
      state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.devopsm71.online -uroot -pRoboshop@1 < /app/schema/{{component}}.sql