groups:
  - name: roboshop-service-alerts
    rules:
    { % for component in components % }      # components is a variable
    - alert: Service Down Alert - {{ item }} service
      expr: node_systemd_unit_state{exported_name="{{ item }}.service", state="active"}
      for: 30s
      labels:
        severity: critical
        appName: {{ item }}
      annotations:
        summary: Server Down on some server - Service Name -{{ item }}.service
    {% endfor %}