groups:
  - name: roboshop-service-alerts
    rules:
    {% for component in components %}      # components is a variable

    - alert: Service Down Alert - {{ component }} service
      expr: node_systemd_unit_state{exported_name="{{ component }}.service", state="active"}
      for: 30s
      labels:
        severity: critical
        appName: {{ component }}
      annotations:
        summary: Server Down on some server - Service Name -{{ component }}.service
    {% endfor %}